### ISSUE TITLE
Missing json definition in go type struct

### ISSUE THREAD

**Issue by qwe7989199** [March-mitsuki/selien#2]
```yaml
selien-version: 0.1.0
definition:
  OwnDataResponse:
    declaration: type-alias
    body:
      type: object
      properties:
        status:
          type: $ref
          uri: "#/definition/statusCode"
        data:
          type: object
          properties:
            common:
              type: array
              items: 
                type: string
            paid:
              type: array
              items:
                type: string
            private:
              type: array
              items: 
                type: string
```
Generates
```go
type OwnDataResponse struct {
	Status StatusCode `json:"status"`
	Data   struct {
		Common  []string `json:"common"`
		Paid    []string `json:"paid"`
		Private []string `json:"private"`
	}
}
```
which is expected to be 
```go
type OwnDataResponse struct {
	Status StatusCode `json:"status"`
	Data   struct {
		Common  []string `json:"common"`
		Paid    []string `json:"paid"`
		Private []string `json:"private"`
	} `json:"data"`
}
```
